{
  "status": "error",
  "message": "Exception: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD70B9C990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"
}